services:
  custom_api:
    container_name: custom_api
    restart: always
    build:
      context: ./custom_api
      dockerfile: Dockerfile
    ports:
      - target: $CUSTOM_API_PORT
        published: $CUSTOM_API_PORT
    environment:
      CUSTOM_API_PORT: $CUSTOM_API_PORT
      CUSTOM_API_USER: $CUSTOM_API_USER
      CUSTOM_API_PASSWORD: $CUSTOM_API_PASSWORD
      OPENAI_API_KEY: $OPENAI_API_KEY
